name: bdtheque-web

services:
  data:
    image: tetram76/bdtheque-web-data
    build:
      context: ./data
      target: production
    ports:
      - "5432:5432"
    networks:
      bdtheque-net:
    environment:
      PGDATA: /var/lib/postgresql/data
    volumes:
      - bdtheque-database:/var/lib/postgresql/data
    env_file:
      - ./deploy.env

  #  data-manager:
  #    image: tetram76/bdtheque-web-data-manager
  #    build:
  #      context: ./data
  #      target: manager
  #    ports:
  #      - "8081:80"
  #    networks:
  #      bdtheque-net:
  #    environment:
  #      PGADMIN_LISTEN_PORT: 80
  #      PGADMIN_DEFAULT_EMAIL: webmaster@tetram.org
  #    volumes:
  #      - bdtheque-pgadmin:/var/lib/pgadmin

  redis:
    image: redis:6.0-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3

  api:
    depends_on:
      - data
    image: tetram76/bdtheque-web-api
    build:
      context: ./api
      target: production
    ports:
      - "8080:3000"
    networks:
      bdtheque-net:
    volumes:
      - bdtheque-config:/etc/bdtheque # :ro
      - bdtheque-secrets:/etc/bdtheque/secrets # :ro
    env_file:
      - ./deploy.env

  front:
    image: tetram76/bdtheque-web-front
    build:
      context: ./front
      target: production
      args:
        NODE_VERSION: 18
    ports:
      - "80:80"
    networks:
      bdtheque-net:
    env_file:
      - ./deploy.env

volumes:
  bdtheque-config:
    external: true

  bdtheque-secrets:
    external: true

  bdtheque-database:
    external: true

  bdtheque-storage:
    external: true

networks:
  bdtheque-net: { }
