namespace BDTheque.Analyzers.Generators;

using BDTheque.Analyzers.Extensions;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

[Generator]
public class MutationImplementationsGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        IncrementalValuesProvider<GeneratorSyntaxContext> classDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                static (s, _) => s is ClassDeclarationSyntax { AttributeLists.Count: > 0 },
                static (ctx, _) => ctx
            )
            .Where(static ctx => ((ClassDeclarationSyntax) ctx.Node).IsAnnotatedWithMutationType(ctx));

        context.RegisterSourceOutput(
            classDeclarations,
            static (sourceContext, generatorContext) => GenerateImplementations(sourceContext, generatorContext)
        );
    }

    private static void GenerateImplementations(SourceProductionContext sourceContext, GeneratorSyntaxContext generatorContext)
    {
        var classDeclaration = (ClassDeclarationSyntax) generatorContext.Node;

        CompilationUnitSyntax compilationUnitSyntax = GenerateCompilationUnit(classDeclaration, generatorContext);

        string sourceText = compilationUnitSyntax.NormalizeWhitespace().ToFullString();
        sourceContext.AddSource($"{classDeclaration.Identifier.Text}.g.cs", sourceText);
    }

    private static CompilationUnitSyntax GenerateCompilationUnit(ClassDeclarationSyntax classDeclaration, GeneratorSyntaxContext context)
    {
        ITypeSymbol entityClassSymbol = classDeclaration.GetEntityTypeFromAttribute(context);
        Compilation compilation = classDeclaration.SemanticModel(context).Compilation;

        ClassDeclarationSyntax mutationsClass = GenerateMutationsClass(classDeclaration);
        if (entityClassSymbol.MutableProperties(compilation).Any(property => property.Type.IsEntityType(compilation)))
            mutationsClass = mutationsClass.WithMembers(
                mutationsClass.Members.Insert(0, GenerateInputInterfaceExtensionDeclaration(entityClassSymbol, compilation))
            );

        return SyntaxFactory.CompilationUnit()
            .AddUsings(
                SyntaxFactory.UsingDirective(SyntaxFactory.IdentifierName(WellKnownDefinitions.InputsNamespaceName))
            )
            .AddMembers(
                SyntaxFactory
                    .NamespaceDeclaration(classDeclaration.ContainingNamespace()) // the generated source is more readable than with a FileScopedNamespaceDeclaration
                    .AddMembers(
                        mutationsClass
                    )
            )
            .NormalizeWhitespace()
            .SetAutoGenerated()
            .ActivateNullability();
    }

    private static ClassDeclarationSyntax GenerateMutationsClass(ClassDeclarationSyntax classDeclaration) =>
        SyntaxFactory.ClassDeclaration(classDeclaration.Identifier)
            .AddModifiers(
                SyntaxFactory.Token(SyntaxKind.PublicKeyword),
                SyntaxFactory.Token(SyntaxKind.StaticKeyword),
                SyntaxFactory.Token(SyntaxKind.PartialKeyword)
            )
            .AddGeneratedAttribute<MutationImplementationsGenerator>();

    private static MethodDeclarationSyntax GenerateInputInterfaceExtensionDeclaration(ITypeSymbol classSymbol, Compilation compilation)
    {
        TypeSyntax entityTypeSyntax = SyntaxFactory.ParseTypeName(classSymbol.Name);

        IdentifierNameSyntax inputIdentifier = SyntaxFactory.IdentifierName("input");
        IdentifierNameSyntax entityIdentifier = SyntaxFactory.IdentifierName("entity");
        IdentifierNameSyntax dbContextIdentifier = SyntaxFactory.IdentifierName("dbContext");

        List<ParameterSyntax> parameters =
        [
            SyntaxFactory.Parameter(inputIdentifier.Identifier).WithType(SyntaxFactory.ParseTypeName("I" + classSymbol.Name + "InputType"))
                .AddModifiers(SyntaxFactory.Token(SyntaxKind.ThisKeyword)),
            SyntaxFactory.Parameter(entityIdentifier.Identifier).WithType(entityTypeSyntax),
            SyntaxFactory.Parameter(dbContextIdentifier.Identifier).WithType(SyntaxFactory.ParseTypeName($"global::{WellKnownDefinitions.BDTheque.Data.DBContext}"))
        ];

        if (classSymbol.MutableProperties(compilation).Any(property => property.Type.IsEntityType(compilation) && !property.Type.IsNullable()))
            parameters.Add(SyntaxFactory.Parameter(SyntaxFactory.Identifier("cancellationToken")).WithType(SyntaxFactory.ParseTypeName("CancellationToken")));

        return SyntaxFactory
            .MethodDeclaration(SyntaxFactory.GenericName("Task").AddTypeArgumentListArguments(entityTypeSyntax), "ApplyTo")
            .AddModifiers(
                SyntaxFactory.Token(SyntaxKind.InternalKeyword),
                SyntaxFactory.Token(SyntaxKind.StaticKeyword)
            )
            .AddParameterListParameters(
                parameters.ToArray()
            )
            .WithExpressionBody(
                SyntaxFactory.ArrowExpressionClause(
                    SyntaxFactory.InvocationExpression(
                        SyntaxFactory.MemberAccessExpression(
                            SyntaxKind.SimpleMemberAccessExpression, inputIdentifier, SyntaxFactory.IdentifierName("ApplyTo")
                        )
                    ).AddArgumentListArguments(
                        SyntaxFactory.Argument(entityIdentifier)
                    ).AddArgumentListArguments(
                        classSymbol.MutableProperties(compilation)
                            .Where(property => property.Type.IsEntityType(compilation))
                            .Select(property => SyntaxFactory.Argument(SearchEntityExpression(property, compilation)))
                            .ToArray()
                    )
                )
            )
            .WithSemicolonToken(SyntaxFactory.Token(SyntaxKind.SemicolonToken));
    }

    private static ExpressionSyntax SearchEntityExpression(IPropertySymbol propertySymbol, Compilation compilation)
    {
        // async serie => serie == null ? null : await dbContext.Series.FindAsync(serie.Id)
        // async editeur => await dbContext.Editeurs.SingleAsync(e => e.Id == editeur.Id, cancellationToken)

        IdentifierNameSyntax parameterIdentifier = SyntaxFactory.IdentifierName(propertySymbol.Name.ToCamelCase());
        IdentifierNameSyntax idIdentifier = SyntaxFactory.IdentifierName("Id");
        MemberAccessExpressionSyntax idAccessExpression = SyntaxFactory.MemberAccessExpression(
            SyntaxKind.SimpleMemberAccessExpression, parameterIdentifier, idIdentifier
        );
        InvocationExpressionSyntax dbSetAccessExpression = SyntaxFactory.InvocationExpression(
            SyntaxFactory.MemberAccessExpression(
                SyntaxKind.SimpleMemberAccessExpression,
                SyntaxFactory.IdentifierName("dbContext"),
                SyntaxFactory.GenericName(SyntaxFactory.Identifier("Set")).AddTypeArgumentListArguments(SyntaxFactory.IdentifierName(propertySymbol.Type.Name))
            )
        );

        CSharpSyntaxNode searchExpression;

        if (propertySymbol.Type.IsNullable())
        {
            // await dbContext.Series.FindAsync(serie.Id)
            AwaitExpressionSyntax searchCallExpression = SyntaxFactory.AwaitExpression(
                SyntaxFactory.InvocationExpression(
                    SyntaxFactory.MemberAccessExpression(
                        SyntaxKind.SimpleMemberAccessExpression, dbSetAccessExpression, SyntaxFactory.IdentifierName("FindAsync")
                    )
                ).AddArgumentListArguments(
                    SyntaxFactory.Argument(
                        propertySymbol.GetMutationType(compilation) == null ? idAccessExpression : parameterIdentifier
                    )
                )
            );

            searchExpression = SyntaxFactory.ConditionalExpression(
                SyntaxFactory.BinaryExpression(
                    SyntaxKind.EqualsExpression, parameterIdentifier, SyntaxFactory.LiteralExpression(SyntaxKind.NullLiteralExpression)
                ),
                SyntaxFactory.LiteralExpression(SyntaxKind.NullLiteralExpression),
                searchCallExpression
            );
        }
        else
        {
            // Expression lambda interne pour le prédicat de SingleAsync (e => e.Id == editeur.Id)
            IdentifierNameSyntax entityIdentifier = SyntaxFactory.IdentifierName("e");
            SimpleLambdaExpressionSyntax predicateLambda = SyntaxFactory.SimpleLambdaExpression(
                SyntaxFactory.Parameter(entityIdentifier.Identifier),
                SyntaxFactory.BinaryExpression(
                    SyntaxKind.EqualsExpression,
                    SyntaxFactory.MemberAccessExpression(SyntaxKind.SimpleMemberAccessExpression, entityIdentifier, idIdentifier),
                    propertySymbol.GetMutationType(compilation) == null ? idAccessExpression : parameterIdentifier
                )
            );

            // Invocation de dbContext.Editeurs.SingleAsync avec la lambda et le cancellationToken
            searchExpression = SyntaxFactory.AwaitExpression(
                SyntaxFactory.InvocationExpression(
                    SyntaxFactory.MemberAccessExpression(
                        SyntaxKind.SimpleMemberAccessExpression, dbSetAccessExpression, SyntaxFactory.IdentifierName("SingleAsync")
                    )
                ).AddArgumentListArguments(
                    SyntaxFactory.Argument(predicateLambda),
                    SyntaxFactory.Argument(SyntaxFactory.IdentifierName("cancellationToken"))
                )
            );
        }

        return SyntaxFactory.ParenthesizedLambdaExpression(
            SyntaxFactory.Token(SyntaxKind.AsyncKeyword),
            SyntaxFactory.ParameterList(SyntaxFactory.SingletonSeparatedList(SyntaxFactory.Parameter(parameterIdentifier.Identifier))),
            SyntaxFactory.Token(SyntaxKind.EqualsGreaterThanToken),
            searchExpression
        );
    }
}
