// ReSharper disable once CheckNamespace
namespace Microsoft.CodeAnalysis.CSharp.Syntax;

public static class CompilationUnitExtensions
{
    public static CompilationUnitSyntax SetAutoGenerated(this CompilationUnitSyntax compilationUnitSyntax) =>
        compilationUnitSyntax.WithLeadingTrivia(
            compilationUnitSyntax.GetLeadingTrivia().Add(
                SyntaxFactory.Comment("// <auto-generated/>")
            )
        );

    public static CompilationUnitSyntax ActivateNullability(this CompilationUnitSyntax compilationUnitSyntax, bool activated = true) =>
        compilationUnitSyntax.WithLeadingTrivia(
            compilationUnitSyntax.GetLeadingTrivia().Add(
                SyntaxFactory.Trivia(SyntaxFactory.NullableDirectiveTrivia(SyntaxFactory.Token(SyntaxKind.EnableKeyword), activated))
            )
        );
}
