namespace BDTheque.Analyzers;

using BDTheque.Analyzers.Extensions;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using SyntaxKind = Microsoft.CodeAnalysis.CSharp.SyntaxKind;

[Generator]
public class MutationInputsGenerator : IIncrementalGenerator
{
    public const string CreateInputTypeSuffix = "CreateInput";
    public const string UpdateInputTypeSuffix = "UpdateInput";
    public const string NestedTypeSuffix = "NestedInput";
    public const string InputsNamespaceName = "BDTheque.Model.Inputs";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        IncrementalValuesProvider<GeneratorSyntaxContext> classDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                static (s, _) => s is ClassDeclarationSyntax { AttributeLists.Count: > 0 },
                static (ctx, _) => ctx
            )
            .Where(static ctx => ((ClassDeclarationSyntax) ctx.Node).IsAnnotatedWithObjectType(ctx));

        context.RegisterSourceOutput(
            classDeclarations,
            static (sourceContext, generatorContext) => GenerateInputTypes(sourceContext, generatorContext)
        );
    }

    private static void GenerateInputTypes(SourceProductionContext sourceContext, GeneratorSyntaxContext generatorContext)
    {
        var classDeclaration = (ClassDeclarationSyntax) generatorContext.Node;
        CompilationUnitSyntax? compilationUnitSyntax = GenerateClassSource(classDeclaration, generatorContext);
        if (compilationUnitSyntax is null) return;

        string sourceText = compilationUnitSyntax.NormalizeWhitespace().ToFullString();
        sourceContext.AddSource($"{classDeclaration.Identifier.Text}Inputs.g.cs", sourceText);
    }

    private static CompilationUnitSyntax? GenerateClassSource(ClassDeclarationSyntax classDeclaration, GeneratorSyntaxContext context)
    {
        if (classDeclaration.SemanticModel(context).GetDeclaredSymbol(classDeclaration) is not { } classSymbol) return null;
        if ((classSymbol.BaseType is not { } baseTypeSymbol) || (baseTypeSymbol.SpecialType == SpecialType.System_Object)) return null;

        const string entitySuffix = "Entity";
        var baseClassName = baseTypeSymbol.ToDisplayParts().Last().ToString();
        if (!baseClassName.EndsWith(entitySuffix))
            return null;
        baseClassName = baseClassName.Substring(0, baseClassName.Length - entitySuffix.Length);

        InterfaceDeclarationSyntax inputInterfaceDeclaration = GenerateInputInterfaceDeclaration(context, classDeclaration);
        ClassDeclarationSyntax[] inputClassesDeclaration = GenerateInputClassesDeclaration(context, classDeclaration, baseClassName, inputInterfaceDeclaration);
        ClassDeclarationSyntax nestedClassDeclaration = GenerateNestedClassDeclaration(context, classDeclaration, baseClassName);

        return SyntaxFactory
            .CompilationUnit()
            .AddUsings(classDeclaration.SyntaxTree.GetCompilationUnitRoot().Members.OfType<BaseNamespaceDeclarationSyntax>().SelectMany(syntax => syntax.Usings).ToArray())
            .AddUsings(
                SyntaxFactory.UsingDirective(SyntaxFactory.IdentifierName(classSymbol.ContainingNamespace.ToDisplayString())),
                SyntaxFactory.UsingDirective(SyntaxFactory.IdentifierName("HotChocolate.Types"))
            )
            .AddMembers(
                SyntaxFactory
                    .NamespaceDeclaration(SyntaxFactory.IdentifierName(InputsNamespaceName)) // the generated source is more readable than with a FileScopedNamespaceDeclaration
                    .AddMembers(
                        inputClassesDeclaration.OfType<MemberDeclarationSyntax>().ToArray()
                    )
                    .AddMembers(
                        inputInterfaceDeclaration,
                        nestedClassDeclaration
                    )
            )
            .NormalizeWhitespace()
            .WithLeadingTrivia(
                SyntaxFactory.Comment("// <auto-generated/>"),
                SyntaxFactory.Trivia(SyntaxFactory.NullableDirectiveTrivia(SyntaxFactory.Token(SyntaxKind.EnableKeyword), true))
            );
    }

    private static InterfaceDeclarationSyntax GenerateInputInterfaceDeclaration(GeneratorSyntaxContext context, ClassDeclarationSyntax classDeclaration) =>
        SyntaxFactory
            .InterfaceDeclaration("I" + classDeclaration.Identifier.Text + "InputType")
            .AddModifiers(SyntaxFactory.Token(SyntaxKind.PublicKeyword))
            .AddGeneratedAttribute<MutationInputsGenerator>()
            .AddMembers(
                classDeclaration.MutableProperties(context)
                    .Select(
                        property =>
                        {
                            TypeSyntax? scalarType = property.GetMutationType(context);

                            return SyntaxFactory
                                .PropertyDeclaration(property.Type, property.Identifier)
                                .AddModifiers(SyntaxFactory.Token(SyntaxKind.PublicKeyword))
                                .WithType(
                                    SyntaxFactory
                                        .GenericName(SyntaxFactory.Identifier("global::HotChocolate.Optional"))
                                        .AddTypeArgumentListArguments(
                                            property.Type.RewriteType(context, syntax => SyntaxFactory.IdentifierName(scalarType == null ? syntax + NestedTypeSuffix : "ushort"))
                                        )
                                )
                                .AddAccessorListAccessors(SyntaxFactory.AccessorDeclaration(SyntaxKind.GetAccessorDeclaration).WithSemicolonToken(SyntaxFactory.Token(SyntaxKind.SemicolonToken)))
                                .WithSemicolonToken(default);
                        }
                    )
                    .Cast<MemberDeclarationSyntax>()
                    .ToArray()
            )
            .AddApplyToMethod(context, classDeclaration);


    private static ClassDeclarationSyntax GenerateInputClassDeclaration(GeneratorSyntaxContext context, ClassDeclarationSyntax classDeclaration, string baseClassName, InterfaceDeclarationSyntax inputInterfaceDeclaration, string classSuffix) =>
        SyntaxFactory
            .ClassDeclaration(classDeclaration.Identifier.Text + classSuffix)
            .WithModifiers(classDeclaration.Modifiers)
            .AddBaseListTypes(
                SyntaxFactory.SimpleBaseType(SyntaxFactory.IdentifierName(baseClassName + classSuffix)),
                SyntaxFactory.SimpleBaseType(SyntaxFactory.IdentifierName(inputInterfaceDeclaration.Identifier))
            )
            .AddGeneratedAttribute<MutationInputsGenerator>()
            .AddMembers(
                classDeclaration.MutableProperties(context)
                    .Select(
                        property =>
                        {
                            TypeSyntax? scalarType = property.GetMutationType(context);

                            return property // duplicate original property with some alterations
                                .WithType(
                                    SyntaxFactory
                                        .GenericName(SyntaxFactory.Identifier("global::HotChocolate.Optional"))
                                        .AddTypeArgumentListArguments(
                                            property.Type.RewriteType(context, syntax => SyntaxFactory.IdentifierName(scalarType == null ? syntax + NestedTypeSuffix : "ushort"))
                                        )
                                )
                                .ApplyMutationType(context, property.Type, scalarType)
                                .AddRequiredAttribute(classSuffix == CreateInputTypeSuffix && property.Type is not NullableTypeSyntax)
                                .WithInitializer(null).WithSemicolonToken(default);
                        }
                    )
                    .Cast<MemberDeclarationSyntax>()
                    .ToArray()
            );

    private static ClassDeclarationSyntax[] GenerateInputClassesDeclaration(GeneratorSyntaxContext context, ClassDeclarationSyntax classDeclaration, string baseClassName, InterfaceDeclarationSyntax inputInterfaceDeclaration) =>
    [
        GenerateInputClassDeclaration(context, classDeclaration, baseClassName, inputInterfaceDeclaration, CreateInputTypeSuffix),
        GenerateInputClassDeclaration(context, classDeclaration, baseClassName, inputInterfaceDeclaration, UpdateInputTypeSuffix)
    ];

    private static ClassDeclarationSyntax GenerateNestedClassDeclaration(GeneratorSyntaxContext context, ClassDeclarationSyntax classDeclaration, string baseClassName) =>
        SyntaxFactory
            .ClassDeclaration(classDeclaration.Identifier.Text + NestedTypeSuffix)
            .WithModifiers(classDeclaration.Modifiers)
            .AddBaseListTypes(
                SyntaxFactory.SimpleBaseType(SyntaxFactory.IdentifierName(baseClassName + NestedTypeSuffix))
            )
            .AddGeneratedAttribute<MutationInputsGenerator>()
            .AddMembers(
                classDeclaration.Members
                    .OfType<PropertyDeclarationSyntax>()
                    .Where(propertySyntax => propertySyntax.IsAnnotatedWithIdType(context))
                    .Select(property => property.AddRequiredAttribute())
                    .Cast<MemberDeclarationSyntax>()
                    .ToArray()
            )
            .AddImplicitConverter(
                classDeclaration
                    .AllMembers(context)
                    .OfType<PropertyDeclarationSyntax>()
                    .OnlyOrDefault(syntax => syntax.IsAnnotatedWithIdType(context))
            );
}
